#'Combine a grinn network queried from grinn internal database to a provided network
#'@description The function combines a grinn network computed from \code{fetchGrinnNetwork} to a network generated by \code{fetchCorrNetwork}, 
#'\code{fetchWGCNAModule}, \code{fetchDiffCorrNetwork} where \code{returnAs = "tab"}. Or it can combine other networks with defined format, see \code{othernw}.
#'@usage combineNetwork(grinnw, othernw, returnAs)
#'@param grinnw list of nodes and edges, queried from grinn internal database using \code{fetchGrinnNetwork}.
#'@param othernw list of nodes and edges, computed from \code{fetchCorrNetwork}, \code{fetchWGCNAModule}, \code{fetchDiffCorrNetwork} 
#'where \code{returnAs = "tab"}, or generated by other methods.
#'If using other methods, the input network must be in the following format:
#'\code{nodes} = data.frame(id,nodename,nodetype) #nodes contain at least 3 columns with defined names
#'\code{edges} = data.frame(source,target,reltype,relname) #edges contain at least 4 columns with defined names
#'\code{othernw} = list(nodes,edges)
#'Also by using other methods, node ids should be converted to grinn ids. It can be done by \code{convertToGrinnID} before generating the input network.
#'@param returnAs string of output type. Specify the type of the returned network. 
#'It can be one of "tab","json","cytoscape", default is "tab". "cytoscape" is the format used in Cytoscape.js
#'@return list of nodes and edges. The list is with the following componens: edges and nodes. Return empty list if error.
#'@author Kwanjeera W \email{kwanich@@ucdavis.edu}
#'@export
#'@seealso \url{http://js.cytoscape.org/}, \code{\link{fetchGrinnNetwork}}, \code{\link{fetchCorrNetwork}}, \code{\link{fetchWGCNAModule}}, \code{\link{fetchDiffCorrNetwork}}
#'@examples
#'# Create metabolite-protein network from the list of metabolites using grinn ids and combine the grinn network to a correlation network
#'kw <- c('X160','X300','X371')
#'grinnnw <- fetchGrinnNetwork(txtInput=kw, from="metabolite", to="protein")
#'dummy <- rbind(nodetype=rep("metabolite"),t(mtcars))
#'colnames(dummy) <- c('X160','X300','X371','X367',paste0('X',sample(400:22000, 28)))
#'corrnw <- fetchCorrNetwork(datNormX=dummy, datNormY=NULL, corrCoef=0.5, pval= 1e-12, method="pearson", returnAs="tab")
#'result <- combineNetwork(grinnnw,corrnw)
#'library(igraph)
#'plot(graph.data.frame(result$edges[,1:2], directed=FALSE))
#'# Create metabolite-protein network from the list of metabolites using grinn ids and combine the grinn network to a provided network
#'txtInput <- list('X371','X783','X1.1')
#'grinnnw <- fetchGrinnNetwork(txtInput, from="metabolite", to="protein")
#'othernw = list()
#'othernw$nodes = data.frame(id=c("X371","X783","XXX","YYY"),nodename=c("X371","X783","XXX","YYY"),nodetype=c("metabolite","metabolite","protein","protein"),stringsAsFactors = FALSE)
#'othernw$edges = data.frame(source=c("X371","X783"),target=c("XXX","YYY"),corr_coef=c(-0.368,0.385),pval=c(0.000927,0.000497),reltype=c("Metabolite_Protein","Metabolite_Protein"),relname=c("CORRELATION","CORRELATION"),stringsAsFactors = FALSE)
#'result <- combineNetwork(grinnnw,othernw)

combineNetwork <- function(grinnw, othernw, returnAs="tab"){
  tryCatch({
    if(!(length(colnames(othernw$nodes)) >= 3) || !(length(colnames(othernw$edges)) >= 4)){
      stop("incorrect number of columns or incorrect column names, \n
           require at least 'id, nodename, nodetype' for nodelist and 'source, target, reltype, relname' for edgelist")
    }
    
    cat("Formating and returning combined network ...\n")
    
    attb = plyr::rbind.fill(grinnw$nodes,othernw$nodes)
    pair = plyr::rbind.fill(grinnw$edges,othernw$edges)
    attb = attb[!duplicated(attb[,1]),]
    colbs = colnames(grinnw$nodes)
    colot = colnames(othernw$nodes)
    cat("Found ",nrow(pair)," relationships...\n")
    
    out = switch(returnAs,
                 tab = list(nodes=attb, edges=pair),
                 json = list(nodes=jsonlite::toJSON(attb), edges=jsonlite::toJSON(pair)),
                 cytoscape = createCyNetwork(attb, pair),
                 stop("incorrect return type"))
  }, error = function(err) {
    print(err)
    pair = data.frame()
    attb = data.frame()
    out <- list(nodes=attb, edges=pair) #return empty list
  }) # END tryCatch
}